name: Aur build
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.6
      - name: Build 
        run: make all
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bare-server-aur
          path: bare-server
