name: Aur build
on:
  workflow_run:
    workflows: ["Build binaries"]
    types:
      completed
  workflow_dispatch:

jobs:
  aur:
    name: Upload to AUR 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Extract tag 
        id: extract_tag
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')"
      - name: Setup SSH Key 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_KEY }}" > ~/.ssh/aur 
          chmod 600 ~/.ssh/aur 
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          echo -e "Host aur.archlinux.org\n\tIdentityFile ~/.ssh/aur\n\tUser aur" > ~/.ssh/config
      - name: Pull changes from AUR 
        run: |
          sed -i "s/pkgver=.*/pkgver=${{ steps.extract_tag.outputs.version }}/" PKGBUILD
          git clone aur@aur.archlinux.org:bare-server-go.git 
          cp -rf ./README.md ./bare-server-go/
          cp -rf ./PKGBUILD ./bare-server-go/
          cp -rf ./LICENSE ./bare-server-go/
          cd bare-server-go
          git config --global user.email "${{ secrets.AUR_EMAIL }}"
          git config --global user.name "${{ secrets.AUR_USERNAME }}"
          cat PKGBUILD
      - name: Validate PKGBUILD 
        uses: hapakaien/archlinux-package-action@v2
        with:
          path: bare-server-go 
          flags: ''
          namcap: false
          srcinfo: true
          updpkgsums: true
      - name: Push changes to AUR 
        run: |
          cd bare-server-go
          git add .
          git commit -m "Update to ${{ steps.extract_tag.outputs.version }}"
          git push
