name: Add release binary
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          name: bare-server-release
          path: bare-server-go
      - name: Upload to release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #get the release event when in beta 
          release=$(gh release list --limit 1 | awk '{print $1}')
          # upload the artifact to the release
          gh release upload $release ./bare-server-go/bin/bare-server-go --clobber
  cleanup:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Purge artifacts
        uses: olpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0
