name: Build, Upload and Release Binaries
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  aur-build:
    name: Build Binary for AUR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.6
      - name: Build (AUR Only)
        run: make linux
      - name: Push to bin/
        uses: EndBug/add-and-commit@v9
        with:
          push: origin HEAD:main
          add: bin/bare-server-go --force
          author_name: motortruck1221
          author_email: motortruck1221@protonmail.com
  aur:
    needs: aur-build
    name: Upload to AUR 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Extract tag 
        id: extract_tag
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')"
      - name: Setup SSH Key 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_KEY }}" > ~/.ssh/aur 
          chmod 600 ~/.ssh/aur 
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          echo -e "Host aur.archlinux.org\n\tIdentityFile ~/.ssh/aur\n\tUser aur" > ~/.ssh/config
      - name: Pull changes from AUR 
        run: |
          sed -i "s/pkgver=.*/pkgver=${{ steps.extract_tag.outputs.version }}/" PKGBUILD
          git clone aur@aur.archlinux.org:bare-server-go.git 
          cp -rf ./README.md ./bare-server-go/
          cp -rf ./PKGBUILD ./bare-server-go/
          cp -rf ./LICENSE ./bare-server-go/
          cd bare-server-go
          git config --global user.email "${{ secrets.AUR_EMAIL }}"
          git config --global user.name "${{ secrets.AUR_USERNAME }}"
          cat PKGBUILD
      - name: Validate PKGBUILD 
        uses: motortruck1221/arch-linux-pkgbuild-package@v2.2.1
        with:
          path: bare-server-go 
          flags: ''
          namcap: false
          srcinfo: true
          updpkgsums: true
      - name: Push changes to AUR 
        run: |
          cd bare-server-go
          git add .
          git commit -m "Update to ${{ steps.extract_tag.outputs.version }}"
          git push
  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.6
      - name: Build (All) 
        run: make all 
      - name: Upload binaries 
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/
          retention-days: 1
  download-upload-release:
    name: Download & Upload Binaries to Release
    runs-on: ubuntu-latest
    needs: build-binaries
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Download binaries 
        uses: actions/download-artifact@v4
        with:
          #download the binaries from the binaries job 
          name: binaries
          path: bin/
          # binaries worflow run id
      - name: Upload to release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #get the release event when in beta 
          release=$(gh release list --limit 1 | awk '{print $1}')
          # upload the artifact to the release
          gh release upload $release bin/bare-server-go --clobber
          gh release upload $release bin/bare-server-go-arm64 --clobber
          gh release upload $release bin/bare-server-go-arm --clobber
          gh release upload $release bin/bare-server-go-386 --clobber
          gh release upload $release bin/bare-server-go.exe --clobber
          gh release upload $release bin/bare-server-go-mac --clobber
          gh release upload $release bin/bare-server-go-mac-arm64 --clobber 
