name: Add release binary
on:
  #when the aur.yml workflow is run and the build job is completed
  workflow_run:
    workflows: ["Aur build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Upload to release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #get the release event when in beta 
          release=$(gh release list --limit 1 | awk '{print $1}')
          # upload the artifact to the release
          gh release upload $release bin/bare-server-go --clobber
 
